version: '3.8'

services:
  app:
    container_name: decomate_app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    container_name: decomate_db
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistencia de datos
    ports:
      - "5432:5432"

volumes:
  postgres_data: